### ISSUE TITLE
Pcap files corrupted

### ISSUE THREAD

**Issue by Baloc** [groud/dpdkcap#1]
Even if there is no traffic coming to the probed interfaces, some files are corrupted when I execute an extract operation with lzop (the program was terminated with the Ctrl+C shortcut).

Example file : http://cloud.laas.fr/index.php/s/zEb0FMXtKtvp6Ef

**Comment by groud** [comment]
Probably related to a segfault.
However the problem should be fixed by the better core management commit : 637465ec9a38159571005c24dd2385b74f8c95ff
