### ISSUE TITLE
Some implementation questions 

### ISSUE THREAD

**Issue by forward32** [groud/dpdkcap#11]
Hello! 

I have a few questions regarding implementation details :
1) if i use N writers i will get N pcap files, but since all writers read data from one ring (write_ring) the order of packets inside pcap files will be undefined, yes?

2) If i want to process 2 ports (for example with - c1 - w1) it will launch 2 capture cores with shared ring (write_ring). Since all writers use the same ring it is possible that writer for port 1 will process packets from port 2, yes?

If i missed some details, please explain me.

Looking forward for your answer, thank you!

**Comment by groud** [comment]
Hello,

This is not the main fork, if you have any other question you should ask them there: [dpdkcap](https://github.com/dpdkcap/dpdkcap). More people should be available to answer :)

Regarding your questions:
1. The order within a single pcap file is preserved, but not from one file to another. If you merge all pcap files the order will be undefined (the timestamp are set in the writing process, not before the ring enqueue. This may be an improvement of the app).

2. Yes, the -c arguments corresponds to the number of capture core for each port, while the -w option corresponds to the total number of writing cores. They all write and read to the same ring.

This is the architecture we use for now, but it could be improved. I am talking about this [here](https://github.com/dpdkcap/dpdkcap/issues/6).

**Comment by forward32** [comment]
Oh sorry, i didn't notice that this isn't main fork.
Anyway, thank you for answer!

So, with current design using for example 1 port with 1 rx, 1 capture core and 2 write cores i will get 2 .pcap files which will contains all packets captured from that port, but this files won't be consistent. I need to merge it or something like that to restore packets flow(order), yes?

**Comment by groud** [comment]
Exactly. :)
Restoring the ordered flow from multiple capture files is not yet possible.

**Comment by forward32** [comment]
I see, thank you very much!
